# Generated by Django 5.0.6 on 2024-06-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm1', '0002_section_num_class_in_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='available_times',
            field=models.ManyToManyField(to='mm1.meetingtime'),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='day',
            field=models.CharField(choices=[('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(choices=[('10:30 - 11:30', '10:30 - 11:30'), ('11:30 - 12:30', '11:30 - 12:30'), ('12:30 - 13:30', '12:30 - 13:30'), ('14:30 - 16:00', '14:30 - 16:00'), ('16:20 - 18:00', '16:20 - 18:00'), ('18:30 - 20:00', '18:30 - 20:00'), ('20:00 - 22:00', '20:00 - 22:00')], default='14:30 - 16:00', max_length=50),
        ),
    ]
